### PR TITLE
Update labeler.yml

### PR DESCRIPTION
**Pull request by ProFireDev**
fix auto pr labeler

### CODE REVIEW

**Review by Aakansh-C — APPROVED** [review]
Dunno what this does, But I trust you

**Comment by ProFireDev** [comment]
manually labeling these while this is down kinda sucks ngl

**Comment by ProFireDev** [comment]
> Dunno what this does, But I trust you

It auto labels the pull requests, it kind of helps sort everything going on in the project board.

**Review by MarkRJJ — APPROVED** [review]
Good catch

**Pull request merged**
